template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju-x-sydlapsk"
__UND2C__ = "sju-x-sydlapsk"
__UNDEFINED__ = "Old Literary Southern Sámi"
__UND__ = "sju-x-sydlapsk"
