template = "https://github.com/giellalt/template-lang-und"
rev_id = 313
template_sha = "818c033010c3b7b906621cdeca79061f50bd93ed"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju-x-sydlapsk"
__UND2C__ = "sju-x-sydlapsk"
__UNDEFINED__ = "18th century Southern Saami"
__UND__ = "sju-x-sydlapsk"
