template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "umes1235"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-sju-x-sydlapsk"
__UND2C__ = "sju-x-sydlapsk"
__UNDEFINED__ = "Old Literary Southern Sámi"
__UND__ = "sju-x-sydlapsk"
